import qualified Parser
import qualified Beautifier
import qualified Generator
import qualified Text.Show.Pretty as Pr

runEvalWith input = do
  let syntax_tree = Parser.parse input
  putStrLn $ "Syntax tree:\n" ++ (Pr.ppShow syntax_tree)

  let ast = Beautifier.beautify syntax_tree
  putStrLn $ "Ast:\n" ++ (Pr.ppShow ast)

  let ir = Generator.generate ast
  putStrLn $ "IR:\n" ++ (Pr.ppShow ir)

main :: IO ()
main = do
  putStrLn "; Generated by HDC"

  program <- getContents
  runEvalWith program
